### ISSUE TITLE
skip block zeroing in lvm thin pool

### ISSUE THREAD

**Issue by rhvgoyal** [projectatomic/docker-storage-setup#10]
By default docker sets up a thin pool with block zeroing disabled in thin pool for performance reasons. As this script sets up a thin pool for docker, mimic docker behavior.

Device mapper developers also have recommended making use of skip block zeroing for performance reasons.

**Comment by cgwalters** [comment]
This was fixed by https://github.com/projectatomic/docker-storage-setup/pull/11
