### ISSUE TITLE
Do not auto extend data lv. Let user use lvm facilities for this as per the need

### ISSUE THREAD

**Issue by rhvgoyal** [projectatomic/docker-storage-setup#13]
Right now docker-storage-setup keeps on extending the size of data volume
as long as there is free space in the pool. So even if a user has left
some space in the pool free for metadata volume extension, that free space
will be consumed by data volume extension.

Now lvm2 has nice capabilities to automatically extend pool (both data and
metadata) when pool is running short on space. Following are two knobs which
one can use for auto extension.

thin_pool_autoextend_threshold = 100
thin_pool_autoextend_percent = 20

By default extension is disabled. One needs to enable it manually by chaning
the value of thin_pool_autoextend_threshold.

In general it is a good idea to know consume all the free pool space until
and use mechanism like extending pool by certain percentage when it hits
threshold. That allows free space in volume group to be shared by other
entities like root which might have to be grown on need basis too.

**Comment by elephantfries** [comment]
@rhvgoyal  I ran into this indirectly with the latest Centos 7 Atomic installation via kickstart. Anaconda fails on this line:

logvol none --thin --size=100000 --poolname=docker-pool --name=docker-pool --vgname=centos

It complains about 'mount point none is invalid'.  This is probably anaconda problem but leaves me with only implicit configuration which then consumes the entire remaining disk space.  The same logvol configuration works fine on Fedora 22 Atomic.

**Comment by rhvgoyal** [comment]
@elephantfries 

I think issue you are facing has nothing to do with this commit. 

You seem to be trying to create a thin volume using anaconda kickstart commands. And I don't know why that is not working.

In fedora atomic, I think we might not be taking this appraoch. We leave free space in root volume group and later during boot, docker-storage-setup sets up the thin pool. Anaconda does not even come into the picture to setup the docker thin pool.

**Comment by rhvgoyal** [comment]
Patches merged. Closing.
