### ISSUE TITLE
dss/tests: error out if docker.service is already running

### ISSUE THREAD

**Issue by stephen679** [projectatomic/docker-storage-setup#147]
docker.service should not be running/active before running tests, because storage configuration and old meta-data may still be in /var/lib/docker. As a user trying to test docker-storage-setup, it would be helpful if ./run-tests.sh errors out and outputs a message that informs us that docker is running and what actions to take to test from a clean slate, instead of continuing to run tests and obtaining results that the user may not have expected.

**Comment by rhvgoyal** [comment]
Sounds like a good idea. Anyway these tests assume we own the box and it is going to interfere with running docker. So making sure docker is not running or making sure there is no metadata in /var/lib/docker/ will help.
