### ISSUE TITLE
consider having LVM calculate metadata size 

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/docker-storage-setup#172]
See https://github.com/projectatomic/docker-storage-setup/pull/171#discussion_r87871678

**Comment by cgwalters** [comment]
I think my bottom line on this is - we're on track to switch to `overlay2`.  I'm not sure how much I want to poke at tweaking devicemapper.

**Comment by rhvgoyal** [comment]
apart from switching to overlay2, current logic is working and nobody has complained. So why to change that unnecessarily. If we face a real issue or data which shows that lvm takes much smarter decisions, then I will be inclined to make the change. Need a good reason to make the change.

**Comment by dustymabe** [comment]
ok, let's close this then as we have decided not to make the change
