### ISSUE TITLE
Add capability to setup lvm thin pool and pass it to docker

### ISSUE THREAD

**Issue by rhvgoyal** [projectatomic/docker-storage-setup#3]
Right now we setup a data lvm and metadata lvm and pass it to docker and docker in turn sets up thin pool using libdevmapper library. Now lvm tools support creation of thin pool and one can create a 
thin pool using lvm and pass it to docker. 

Advantage of this approach is that lvm can do all the maintenace of pool like automatic resizing and
doing metadata checks when pool is activated etc.

So this should turn out to be a better approach.

**Comment by cgwalters** [comment]
This was merged.
