### ISSUE TITLE
Provide a way to avoid running out of metadata space on devicemapper thinp volume

### ISSUE THREAD

**Issue by jeremyeder** [projectatomic/docker-storage-setup#30]
There are been a handful of cases where users are running out of space on their metadata volumes.  

This was mostly caused by lack of garbage collection in OpenShift and Kubernetes (which has since been implemented and resolved, lessening the urgency of this issue).

But, we want to do a better job avoiding this situation regardless, so ... based on feedback from internal and the field, we would like a way to automatically extend the metadata device using some free space remaining in the volume group.

See #28 

/cc @rhvgoyal

**Comment by rhvgoyal** [comment]
Now by default both data volume and metadata volume are extended as they start filling up.

Closing issue.
