### ISSUE TITLE
Add skeleton /etc/sysconfig/docker-storage-setup

### ISSUE THREAD

**Issue by jeremyeder** [projectatomic/docker-storage-setup#55]
We want to encourage the use of LVM to manage docker's storage.  Our documentation instructs users to copy over /usr/lib/docker-storage-setup/docker-storage-setup to /etc/sysconfig/docker-storage-setup in order to customize defaults.

RHEL users are accustomed to looking in /etc/sysconfig to customize services, docker is no exception:

```
# rpm -qc docker
/etc/sysconfig/docker
/etc/sysconfig/docker-network
/etc/sysconfig/docker-storage
```

The lack of any /etc/sysconfig/docker-storage-setup in our package leads to some confusion about why that file does not exist.

This PR is to create a placeholder file at /etc/sysconfig/docker-storage-setup that instructs users where to find documentation on how to use docker-storage-setup, and brings docker-storage-setup in-line with the rest of the docker package's config files:

**Comment by rhvgoyal** [comment]
@jeremyeder 

Will above patch do?

**Comment by rhvgoyal** [comment]
I think I will need a directive in spec file to not overwrite /etc/sysconfig/docker-storage-setup over upgrade. Instead save it in .rpmsave. I forget to remember what was that directive.

**Comment by rhvgoyal** [comment]
Patch merged. Closing issue.
