### ISSUE TITLE
Root filesystem is not grown

### ISSUE THREAD

**Issue by sdodson** [projectatomic/docker-storage-setup#7]
If I'm reading the script correctly only the root logical volume is resized not the filesystem on top of it. Is the user expected to grow that after the fact or as needed?

**Comment by cgwalters** [comment]
Docker itself implements filesystem creation on top of the thin pool.  Are you seeing a specific problem?

**Comment by sdodson** [comment]
I have not used docker-storage-setup to resize the root LV myself. This line seems to do just that however it doesn't grow the filesystem. Though given more recent discussions I'm not sure we want to.

https://github.com/projectatomic/docker-storage-setup/blob/master/docker-storage-setup.sh#L314

**Comment by cgwalters** [comment]
Ah sorry, I read this too quickly.  Indeed, the script not resizing the FS is a bug...which I think may be covered up by `cloud-init`.  So far most of the typical use cases for resizing the root volume have been around the cloud, where we expect `cloud-init` to run.
