### ISSUE TITLE
Devices /dev/cciss/c0d1 detected as partition

### ISSUE THREAD

**Issue by baboune** [projectatomic/docker-storage-setup#99]
Hi,

Specifying DEVS="/dev/cciss/c0d1" which is a correct device label fails with the following error:
"Partition specification unsupported at this time."

The following on line 426
```
    if [[ $dev =~ .*[0-9]$ ]]; then
       Fatal "Partition specification unsupported at this time."
    fi
```
Identifies any number as a partition which is false in the above case.

/dev/cciss/c0d1 is the device name of a logical drive on an HP DL 380 server using a RAID controller.

My suggestion would be to remove the test for the number as it is not sufficient, and creates false answers.

**Comment by baboune** [comment]
Note that disabling the lines in question is not sufficient:

```
docker-storage-setup 
Checking that no-one is using this disk right now ... OK

Disk /dev/cciss/c0d1: 931.5 GiB, 1000171331584 bytes, 1953459632 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x6073abbd

Old situation:

>>> Script header accepted.
>>> Created a new DOS disklabel with disk identifier 0xdea5060a.
Failed to add partition: Numerical result out of range
Leaving.
```

**Comment by rhvgoyal** [comment]
Yes, this is a very crude check and does not work with all the devices. (including loop devices). I think docker-storage-setup requires better check for partition. Also may be we should use `parted` instead of `sfdisk` to partition the disk.

**Comment by baboune** [comment]
Using VG solved my problem... 

Any ideas on how to test for partition...

**Comment by rhvgoyal** [comment]
One simple idea could be to check `/sys/block/` and see if passed in device name is present there or not. If it is present, then it is a block device and not a partition device.

**Comment by jeremyeder** [comment]
reported with an Intel P3700 NVME device which the kernel calls ```/dev/nvme0n1```

**Comment by rhvgoyal** [comment]
CC @shishir-a412ed
